---
efi:
    mountPoint: "/boot/efi"
    recommendedSize: 512MiB
    minimumSize: 32MiB
    label: "EFI"
userSwapChoices:
    - none
    - small
    - suspend
    - file
luksGeneration: luks2
drawNestedPartitions: false
alwaysShowPartitionLabels: true
allowManualPartitioning: true
showNotEncryptedBootMessage: true
initialPartitioningChoice: none
initialSwapChoice: none
defaultFileSystemType: ext4
availableFileSystemTypes:
    - ext4
    - btrfs
    - xfs
requiredStorage: 20.0
