#!/bin/sh
set -eu

: "${DEBIAN_SUITE:=trixie}"
: "${DEBIAN_MIRROR:=https://deb.debian.org/debian}"
: "${ARCHITECTURE:=amd64}"

lb config noauto \
  --mode debian \
  --distribution "$DEBIAN_SUITE" \
  --architectures "$ARCHITECTURE" \
  --archive-areas "main contrib non-free-firmware" \
  --mirror-bootstrap "$DEBIAN_MIRROR" \
  --mirror-chroot "$DEBIAN_MIRROR" \
  --mirror-binary "$DEBIAN_MIRROR" \
  --mirror-chroot-security "https://security.debian.org/debian-security" \
  --mirror-binary-security "https://security.debian.org/debian-security" \
  --binary-images iso-hybrid \
  --debian-installer live \
  --apt-recommends false \
  --apt-indices false \
  --debian-installer-gui true \
  --bootappend-live "boot=live components quiet splash username=datya locales=en_US.UTF-8 keyboard-layouts=us" \
  --memtest none \
  --iso-application "Datya Linux" \
  --iso-volume "DATYA_LINUX" \
  --iso-publisher "Datya Linux contributors" \
  --iso-preparer "Datya reproducible live-build" \
  --firmware-binary true \
  --firmware-chroot true \
  --checksums sha256
