---
modules:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
  - bootloader
  - packages
  - unpackfs
  - mount
  - fstab
  - machineid
  - locale
  - keyboard
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - umount
branding: datya
oem:
  show: false
sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
    exec:
      - partition
      - unpackfs
      - mount
      - fstab
      - machineid
      - locale
      - keyboard
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - bootloader
      - packages
      - umount
